explictly close verticle on stop to prevent OSGi shutdown errors
avoid an error from Vert.x background threads on Minecraft server stop,
when running under OSGi... this helps for one of the errors (the one
from the SockJSSession), but there is still this one (just ignore it):

[03:33:12 ERROR] [io.vertx.core.impl.ContextImpl]: Unhandled exception
java.lang.NoClassDefFoundError: io/vertx/core/file/FileSystemException
	at io.vertx.core.file.impl.FileSystemImpl.deleteInternal(FileSystemImpl.java:620)
~[?:?]
	at io.vertx.core.file.impl.FileSystemImpl.deleteRecursive(FileSystemImpl.java:228)
~[?:?]
	at io.vertx.core.impl.FileResolver.deleteCacheDir(FileResolver.java:315)
~[?:?]
	at io.vertx.core.impl.FileResolver.close(FileResolver.java:97) ~[?:?]
	at io.vertx.core.impl.VertxImpl.deleteCacheDirAndShutdown(VertxImpl.java:781)
~[?:?]
	at io.vertx.core.impl.VertxImpl.lambda$null$6(VertxImpl.java:556)
~[?:?]
	at io.vertx.core.impl.VertxImpl.lambda$closeClusterManager$4(VertxImpl.java:507)
~[?:?]
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[6_netty-common-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
[6_netty-common-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
[6_netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
[6_netty-common-4.1.16.Final.jar:4.1.16.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.ClassNotFoundException: Unable to load class
'io.vertx.core.file.FileSystemException' because the bundle wiring for
io.vertx.core is no longer valid.
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1539)
~[ch.vorburger.minecraft.osgi-1.0.0-SNAPSHOT-all.jar:?]
	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:79)
~[ch.vorburger.minecraft.osgi-1.0.0-SNAPSHOT-all.jar:?]
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2018)
~[ch.vorburger.minecraft.osgi-1.0.0-SNAPSHOT-all.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
	... 13 more