shadow include Netty and more Vert.x.. but NOK, need to shade
because Minecraft Server uses (a very OLD version of!) Netty itself:

java.lang.NoSuchMethodError:
io.netty.util.NetUtil.isIpV4StackPreferred()Z
	at io.netty.resolver.dns.DnsNameResolver.<clinit>(DnsNameResolver.java:103)
~[web-1.0.0-SNAPSHOT-all.jar:?]