remove VertxStart undeploy() in stop(), probably not required
[vert.x-eventloop-thread-0] ERROR io.vertx.core.impl.DeploymentManager -
Undeploy failed
java.lang.IllegalStateException: Already undeployed
	at io.vertx.core.impl.DeploymentManager$DeploymentImpl.doUndeploy(DeploymentManager.java:548)
	at io.vertx.core.impl.DeploymentManager$DeploymentImpl.undeploy(DeploymentManager.java:543)
	at io.vertx.core.impl.DeploymentManager.undeployVerticle(DeploymentManager.java:255)
	at io.vertx.core.impl.DeploymentManager.undeployAll(DeploymentManager.java:280)
	at io.vertx.core.impl.VertxImpl.lambda$close$10(VertxImpl.java:523)
	at io.vertx.core.impl.CloseHooks.run(CloseHooks.java:100)
	at io.vertx.core.impl.VertxImpl.close(VertxImpl.java:522)
	at io.vertx.core.impl.VertxImpl.close(VertxImpl.java:493)
	at ch.vorburger.minecraft.storeys.web.VertxStarter.stop(VertxStarter.java:86)